SELECT * FROM orders;
SELECT * FROM order_items;

-- Total_revenue
Select sum(coalesce(total_amount, 0)) as total_revenue
From orders;

--Total_orders
Select count(*) as total_orders
From orders;

-- Average order value
Select AVG(total_amount) as AOV
from orders;

-- Total Revenue per Product
Select product_id,
sum(quantity * price) as total_product_revenue
From order_items
Group by product_id
Order by total_product_revenue desc;

-- Revenue per customer 
SELECT customer_id, 
       SUM(total_amount) AS total_revenue
FROM orders
GROUP BY customer_id
ORDER BY total_revenue DESC
LIMIT 3;

-- Total revenue generated by each customer for every specific product 
Select o.customer_id,
i.product_id,
Sum(i.quantity * i.price) as total_spent
From orders o
Join order_items i
On o.order_id = i.order_id
Group by o.customer_id,
i.product_id
Order by total_spent DESC;


-- Top 2 products with highest money spend by customers
Select *
From (
Select 
o.customer_id,
i.product_id,
Sum(quantity * price) as total_spent,
row_number() over (partition by o.customer_id order by Sum(quantity*price) Desc) as rnk
from orders o 
Join order_items i
On o.order_id = i.order_id
group by o.customer_id, i.product_id
) t
Where rnk <= 2;
